"""remove book author_id

Revision ID: 0ccc990d22c4
Revises: e4289a747ca0
Create Date: 2025-03-04 21:13:53.569918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0ccc990d22c4'
down_revision: Union[str, None] = 'e4289a747ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
