"""removed book author_id field

Revision ID: 4a094f813792
Revises: ce3c092243e2
Create Date: 2025-03-04 21:12:52.988328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4a094f813792'
down_revision: Union[str, None] = 'ce3c092243e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
